// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufwvyzayvsjbrltjywps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmd3Z5emF5dnNqYnJsdGp5d3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NTU0NjQsImV4cCI6MjA1MjQzMTQ2NH0.exTImsrJpdL-xHgjv8AjZvIUQBPMsa2z0SskcvdXcxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);